#!/usr/bin/env bash

set -e
set -x


flake8 app --exclude=app/db/migrations
mypy --disallow-untyped-defs --follow-imports=skip app

black --check app --diff
isort --recursive --check-only --multi-line=3 --trailing-comma --line-width 88 --force-grid-wrap=0 --combine-as app
